apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fraatilaa
  namespace: leesah-quiz
  labels:
    team: leesah-quiz
spec:
  ingresses:
    - https://fraatilaa.dev.intern.nav.no
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    initialDelay: 30
    path: isalive
  readiness:
    initialDelay: 30
    path: isready
  replicas:
    max: 1
    min: 1
  kafka:
    pool: nav-dev
  prometheus:
    enabled: true
    path: /metrics
  env:
    - name: QUIZ_TOPIC
      value: "leesah-quiz.leesah-rapid-v2"